### ISSUE TITLE
Line references on GitHub don't work

### ISSUE THREAD

**Issue by ArturKovacs** [forivall/github-custom-tab-size#1]
Hi, thanks for publishing this to the Firefox addons page!

There's only one issue that I'm facing with this; visiting a github URL that referes to a line or a range of lines will result in loading the page without jumping to the line. For example a URL like this: [`https://github.com/forivall/github-default-tab-size/blob/8b53c56458172343d18be862388e7b8dc21d5200/src/content.js#L10`](https://github.com/forivall/github-default-tab-size/blob/8b53c56458172343d18be862388e7b8dc21d5200/src/content.js#L10)

**Comment by forivall** [comment]
fixed! now i just need to remember how to publish it again 😛

**Comment by forivall** [comment]
published!
